package com.nokia.sanjay;

import com.nokia.sanjay.apis.RegexpMatchCalculator;
import com.nokia.sanjay.exceptions.RegexpException;

/**
 * 
 * @author <a href=
 *         "https://www.youracclaim.com/badges/1cacfc10-a704-44ed-94b4-1cd7abbfd168/public_url"
 *         style="color:red; font-size:16; "><em>Sanjay Chauhan</em></a>
 */

public class Tester {

	public static void main(String[] args) {

		RegexpMatchCalculator regexpCalculator = new RegexpMatchCalculatorImpl();

		try {

			regexpCalculator.findRegexpMatch("	\r\n" + "$BEGIN$ 6871_2\r\n"
					+ "LST SUB: ISDN=\"94755841314\", DETAIL=TRUE;\r\n"
					+ "+++    HLR9820        2019-02-15 17:57:25\r\n" + "SMU    #087444\r\n"
					+ "%%  LST SUB: ISDN=\"94755841314\", DETAIL=TRUE;%%\r\n"
					+ "SUCCESS0001:Operation is successful\r\n" + "\r\n" + "                         HLRSN = 31\r\n"
					+ "                          IMSI = 413050114506123\r\n"
					+ "                          ISDN = 94755841314\r\n" + "                       ISDN_ID = 1\r\n"
					+ "                   DEFAULTCALL = Telephony (TS11)\r\n"
					+ "                        DSCODE = Telephony (TS11)\r\n"
					+ "                      CardType = SIM\r\n" + "                           NAM = BOTH\r\n"
					+ "                      CATEGORY = COMMON\r\n" + "\"LOCK\"\r\n"
					+ "                            IC = FALSE\r\n" + "                            OC = FALSE\r\n"
					+ "\r\n" + "                      GPRSLOCK = FALSE\r\n" + "\r\n" + "\"SABLOCK\"\r\n"
					+ "                            IC = FALSE\r\n" + "                            OC = FALSE\r\n"
					+ "\r\n" + "\"Basic Service\"\r\n" + "                    Telephony (TS11)\r\n"
					+ "                    Emergency Call (TS12)\r\n"
					+ "                    Short Message MT_PP (TS21)\r\n"
					+ "                    Short Message MO_PP (TS22)\r\n"
					+ "                    General-DataCDS  (BS30)\r\n"
					+ "                   DefaultCall = Telephony (TS11)\r\n" + "\r\n" + "\"ODB Data\"\r\n"
					+ "                         ODBSS = FALSE\r\n" + "                         ODBOC = NOBOC\r\n"
					+ "                         ODBIC = NOBIC\r\n" + "                        ODBPB1 = FALSE\r\n"
					+ "                        ODBPB2 = FALSE\r\n" + "                        ODBPB3 = FALSE\r\n"
					+ "                        ODBPB4 = FALSE\r\n" + "                       ODBENTE = FALSE\r\n"
					+ "                       ODBINFO = FALSE\r\n" + "                       ODBROAM = BROHPLMNC\r\n"
					+ "                        ODBRCF = NOBRCF\r\n" + "                        ODBECT = NOBECT\r\n"
					+ "                       ODBDECT = FALSE\r\n" + "                       ODBMECT = FALSE\r\n"
					+ "                        ODBPOS = NOBPOS\r\n" + "                    ODBPOSTYPE = BOTH\r\n"
					+ "\r\n" + "\"SS Data\"\r\n" + "                           CFU = PROV\r\n"
					+ "                           NCS = TRUE\r\n" + "                           COU = SUBSCRIBER\r\n"
					+ "                           FTN = 94755841891\r\n" + "                           BSG = TS1X\r\n"
					+ "                        STATUS = PROV | REG\r\n"
					+ "                           FTN = 94755841891\r\n" + "                           BSG = BS3X\r\n"
					+ "                        STATUS = PROV | REG | ACT\r\n"
					+ "                           CFB = PROV\r\n" + "                           NFS = FALSE\r\n"
					+ "                           NCS = FALSE\r\n" + "                           COU = SUBSCRIBER\r\n"
					+ "                           FTN = 94751111111\r\n" + "                           BSG = TS1X\r\n"
					+ "                        STATUS = PROV | REG | ACT\r\n" + "                         \r\n"
					+ "                        \r\n" + "                           CFD = PROV\r\n"
					+ "                           NFS = FALSE\r\n" + "                           NCS = FALSE\r\n"
					+ "                   SUPINTERCFD = FALSE\r\n" + "                      VALIDCCF = CFNRc\r\n"
					+ "                           FTN = 94751111111\r\n" + "                           BSG = TS1X\r\n"
					+ "                  NotReplyTime = 30\r\n" + "                        STATUS = PROV | REG\r\n"
					+ "                            CD = NOTPROV\r\n" + "                          BAOC = NOTPROV\r\n"
					+ "                          BOIC = PROV\r\n" + "                      BOICEXHC = NOTPROV\r\n"
					+ "                          BORO = NOTPROV\r\n" + "                          BAIC = NOTPROV\r\n"
					+ "                       BICROAM = NOTPROV\r\n" + "                         CBCOU = SUBSCRIBER\r\n"
					+ "                          CLIP = PROV\r\n" + "                          CLIR = NOTPROV\r\n"
					+ "                          COLP = NOTPROV\r\n" + "                          COLR = NOTPROV\r\n"
					+ "                           ECT = NOTPROV\r\n" + "                            CW = PROV\r\n"
					+ "                           BSG = TS1X\r\n" + "                         CWAIT = PROV | ACT\r\n"
					+ "                           BSG = BS3X\r\n" + "                         CWAIT = PROV | ACT\r\n"
					+ "                          HOLD = PROV\r\n" + "                          MPTY = PROV\r\n"
					+ "                            MC = NOTPROV\r\n" + "                          AOCI = NOTPROV\r\n"
					+ "                          AOCC = NOTPROV\r\n" + "                           CUG = NOTPROV\r\n"
					+ "                          UUS1 = NOTPROV\r\n" + "                          UUS2 = NOTPROV\r\n"
					+ "                          UUS3 = NOTPROV\r\n" + "                         SMSCF = NOTPROV\r\n"
					+ "             plmn-specificSS-1 = NOTPROV\r\n" + "             plmn-specificSS-2 = NOTPROV\r\n"
					+ "             plmn-specificSS-3 = NOTPROV\r\n" + "             plmn-specificSS-4 = NOTPROV\r\n"
					+ "             plmn-specificSS-5 = NOTPROV\r\n" + "             plmn-specificSS-6 = NOTPROV\r\n"
					+ "             plmn-specificSS-7 = NOTPROV\r\n" + "             plmn-specificSS-8 = NOTPROV\r\n"
					+ "             plmn-specificSS-9 = NOTPROV\r\n" + "             plmn-specificSS-A = NOTPROV\r\n"
					+ "             plmn-specificSS-B = NOTPROV\r\n" + "             plmn-specificSS-C = NOTPROV\r\n"
					+ "             plmn-specificSS-D = NOTPROV\r\n" + "             plmn-specificSS-E = NOTPROV\r\n"
					+ "             plmn-specificSS-F = NOTPROV\r\n" + "                          CNAP = NOTPROV\r\n"
					+ "            allplmn-specificSS = NOTPROV\r\n" + "\"TIF-CSI\"\r\n"
					+ "                        TIFCSI = PROV\r\n" + "\"VLR/SGSN Roaming Restrict\"\r\n"
					+ "                       VLRLIST = 2\r\n"
					+ "                       TPLNAME = Airtel_Roaming_VLR\r\n"
					+ "                      SGSNLIST = 2\r\n" + "                       TPLNAME = AIRTEL postpaid\r\n"
					+ "\"GPRS Data\"\r\n" + "                 CHARGE_GLOBAL = NORMAL\r\n"
					+ "                        CNTXID = 1\r\n" + "                       PDPTYPE = IPV4\r\n"
					+ "                        ADDIND = DYNAMIC ADDRESS\r\n"
					+ "                        RELCLS = ACKRLCPRODT\r\n" + "                      DELAYCLS = DELAY2\r\n"
					+ "                        PRECLS = NORMAL\r\n" + "                       PEAKTHR = 4000 OCT\r\n"
					+ "                       MEANTHR = BEST_EFFORT\r\n" + "                    ARPRIORITY = NORMAL\r\n"
					+ "                        ERRSDU = NODETECT\r\n" + "                      DELIVERY = NO\r\n"
					+ "                    TRAFFICCLS = INTERACT\r\n" + "                    MAXSDUSIZE = 1500 OCT\r\n"
					+ "                      MAXBRUPL = 1024K\r\n" + "                        RESBER = 0.0001\r\n"
					+ "                        SDUERR = 0.00001\r\n" + "                   TRANSFERDEL = 90MS\r\n"
					+ "                    TRAFFICPRI = PRIORITY2\r\n" + "                     MAXGBRUPL = 1K\r\n"
					+ "                     MAXGBRDWL = 1K\r\n" + "                   MAXEXTBRDWL = 21M\r\n"
					+ "                           APN = airtellive\r\n" + "                         VPLMN = FALSE\r\n"
					+ "                        CHARGE = NORMAL\r\n" + "\r\n"
					+ "                          SMDP = MSC\r\n" + "                        NLRInd = NONE\r\n"
					+ "                           ALS = NOTPROV\r\n" + "                          VVDN = NOTPROV\r\n"
					+ "                           ARD = NOTPROV\r\n" + "                          CARP = NOTPROV\r\n"
					+ "                      RROption = ALL_PLMNS\r\n" + "                           VBS = NOTPROV\r\n"
					+ "                          VGCS = NOTPROV\r\n" + "                         EMLPP = NOTPROV\r\n"
					+ "                        FMInit = NOTPROV\r\n" + "                  FMSupervisor = NOTPROV\r\n"
					+ "                      FMRemote = NOTPROV\r\n" + "                           IST = NOTPROV\r\n"
					+ "                           DIC = NOTPROV\r\n" + "\r\n"
					+ "\"Dynamic Status Information For GSM\"\r\n" + "                        VlrNum = 947500002\r\n"
					+ "                        MscNum = 947500002\r\n" + "            MsPurgedForNonGprs = FALSE\r\n"
					+ "                    VLRInHplmn = TRUE\r\n" + "              VLRInHomeCountry = TRUE\r\n"
					+ "                     VLRInArea = FALSE\r\n" + "                RequireCheckSS = FALSE\r\n"
					+ "RoamingRestrictInMscDueToUnsupportedFeature\r\n" + "                               = FALSE\r\n"
					+ "    MscOrVlrAreaRoamingRestrict\r\n" + "                               = FALSE\r\n"
					+ "    ODBarredForUnsupportedCamel\r\n" + "                               = FALSE\r\n"
					+ "          SupportedCamelPhase1 = TRUE\r\n" + "          SupportedCamelPhase2 = TRUE\r\n"
					+ "          SupportedCamelPhase3 = TRUE\r\n" + "          SupportedCamelPhase4 = FALSE\r\n"
					+ "               SRIMsrnCfActive = TRUE\r\n"
					+ "           ZoneCodeStatusAtMsc = zoneCodesSupported\r\n"
					+ "          longGroupIDSupported = FALSE\r\n" + "             basicISTSupported = FALSE\r\n"
					+ "           istCommandSupported = FALSE\r\n" + "   SuperChargerSupportedForGsm = FALSE\r\n"
					+ "                ECATEGORYAtMsc = FALSE\r\n" + "                        LSFLAG = FALSE\r\n"
					+ "                     CSUPLTIME = 2019-02-14 22:41:26\r\n" + "\r\n"
					+ "            BaocForVlrRestrict = FALSE\r\n" + "\r\n"
					+ "\"Dynamic Status Information For GPRS\"\r\n" + "                       SgsnNum = 947500015\r\n"
					+ "               SgsnAddressType = IPV4\r\n"
					+ "                   SgsnAddress = 117.99.129.117\r\n"
					+ "                   SgsnInHplmn = TRUE\r\n" + "               MsPurgedForGprs = FALSE\r\n"
					+ "             SgsnInHomeCountry = TRUE\r\n" + "                    SgsnInArea = FALSE\r\n"
					+ "    RoamingRestrictInSgsnDueToUnsupportedFeature\r\n"
					+ "                               = FALSE\r\n" + "       SgsnAreaRoamingRestrict = FALSE\r\n"
					+ "    ODBarredForUnsupportedCamelForGprs\r\n" + "                               = FALSE\r\n"
					+ "                     PSUPLTIME = 2019-02-06 09:13:36\r\n"
					+ "          SupportedCamelPhase3 = TRUE\r\n" + "          SupportedCamelPhase4 = FALSE\r\n"
					+ "  SuperChargerSupportedForGprs = FALSE\r\n"
					+ "          ZoneCodeStatusAtSgsn = zoneCodesSupported\r\n"
					+ "\"Short Message Dynamic Data for GSM\"\r\n" + "                          MCEF = FALSE\r\n"
					+ "                          MNRF = FALSE\r\n"
					+ "                          MNRR = No Reason for Non-GPRS\r\n" + "\r\n"
					+ "\"Short Message Dynamic Data for GPRS\"\r\n" + "                          MCEF = FALSE\r\n"
					+ "                          MNRG = FALSE\r\n" + "                          MNRR = No Reason\r\n"
					+ "    SupportedShortMessageMT-PP = FALSE\r\n" + "    SupportedShortMessageMO-PP = FALSE\r\n"
					+ "\r\n" + "\"ODB Supported Features For GSM\"\r\n" + "                BarredSSAccess = TRUE\r\n"
					+ "    BarredOutgoingEntertainmentCall\r\n" + "                               = TRUE\r\n"
					+ "    BarredOutgoingInformationCall\r\n" + "                               = TRUE\r\n"
					+ "    BarredOutgoingInternationalCallExHC\r\n" + "                               = TRUE\r\n"
					+ "    BarredOutgoingInternationalCall\r\n" + "                               = TRUE\r\n"
					+ "         BarredAllOutgoingCall = TRUE\r\n" + "                  BarredAllECT = TRUE\r\n"
					+ "           BarredChargeableECT = TRUE\r\n" + "        BarredInternationalECT = TRUE\r\n"
					+ "           BarredInterzonalECT = TRUE\r\n" + "                    BarredDECT = TRUE\r\n"
					+ "                    BarredMECT = TRUE\r\n" + "\r\n" + "\"ODB Supported Features For GPRS\"\r\n"
					+ "         BarredAllOutgoingCall = TRUE\r\n" + "    BarredOutgoingInternationalCall\r\n"
					+ "                               = TRUE\r\n" + "    BarredOutgoingInternationalCallExHC\r\n"
					+ "                               = TRUE\r\n" + "    Barring of Packet Oriented Services\r\n"
					+ "                               = TRUE\r\n" + "\r\n" + "\"Supported LCS\"\r\n"
					+ "    MSC Supported LCS Capability Set1\r\n" + "                               = TRUE\r\n"
					+ "    MSC Supported LCS Capability Set2\r\n" + "                               = TRUE\r\n"
					+ "    SGSN Supported LCS Capability Set2\r\n" + "                               = FALSE\r\n"
					+ "\r\n" + "\"Featured Service Supported Features\"\r\n"
					+ "                           ALS = FALSE\r\n" + "                          VVDN = FALSE\r\n"
					+ "\r\n" + "\r\n" + "Total count = 233\r\n" + "\r\n" + "There is together 1 report\r\n" + "\r\n"
					+ "---   END\r\n" + "\r\n" + "$END$ 6871_2\r\n" + "\r\n" + "         ");

		} catch (RegexpException e) {

			System.out.println(e.getErrorMessage());
			System.out.println(e.getErrorCode());

		} catch (Throwable ex) {

			System.out.println("Unexpected error occured! Reason : " + ex.getMessage());

		}

	}

}
